/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorBus;
import controlador.ControladorChofer;
import controlador.ControladorCliente;
import controlador.ControladorPedido;
import controlador.ControladorReserva;
import controlador.ControladorRuta;

/**
 *
 * @author eduar
 */
public class VistaPrincipal extends javax.swing.JFrame {
    ControladorBus controladorBus;
    ControladorCliente controladorCliente;
    ControladorPedido controladorPedido;
    ControladorChofer controladorChofer;
    ControladorRuta controladorRuta;
    ControladorReserva controladorReserva;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        controladorBus = new ControladorBus();
        controladorCliente = new ControladorCliente();
        controladorPedido = new ControladorPedido();
        controladorChofer = new ControladorChofer();
        controladorRuta = new ControladorRuta();
        controladorReserva = new ControladorReserva();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        dkpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuRegistro = new javax.swing.JMenu();
        mniBuses = new javax.swing.JMenuItem();
        mniChofer = new javax.swing.JMenuItem();
        mniClientes = new javax.swing.JMenuItem();
        mniRuta = new javax.swing.JMenuItem();
        mnuOperaciones = new javax.swing.JMenu();
        mniPedidos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniReserva = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dkpPrincipalLayout = new javax.swing.GroupLayout(dkpPrincipal);
        dkpPrincipal.setLayout(dkpPrincipalLayout);
        dkpPrincipalLayout.setHorizontalGroup(
            dkpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        dkpPrincipalLayout.setVerticalGroup(
            dkpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        mnuRegistro.setText("Registro");

        mniBuses.setText("Buses");
        mniBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBusesActionPerformed(evt);
            }
        });
        mnuRegistro.add(mniBuses);

        mniChofer.setText("Chofer");
        mniChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChoferActionPerformed(evt);
            }
        });
        mnuRegistro.add(mniChofer);

        mniClientes.setText("Clientes");
        mniClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClientesActionPerformed(evt);
            }
        });
        mnuRegistro.add(mniClientes);

        mniRuta.setText("Rutas");
        mniRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRutaActionPerformed(evt);
            }
        });
        mnuRegistro.add(mniRuta);

        jMenuBar1.add(mnuRegistro);

        mnuOperaciones.setText("Operaciones");

        mniPedidos.setText("Pedidos");
        mniPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPedidosActionPerformed(evt);
            }
        });
        mnuOperaciones.add(mniPedidos);

        jMenuBar1.add(mnuOperaciones);

        jMenu3.setText("Reservas");

        mniReserva.setText("Reserva");
        mniReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReservaActionPerformed(evt);
            }
        });
        jMenu3.add(mniReserva);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBusesActionPerformed
        VistaBus vistaBus = new VistaBus(controladorBus);
        dkpPrincipal.add(vistaBus);
        vistaBus.setVisible(true);
    }//GEN-LAST:event_mniBusesActionPerformed

    private void mniClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClientesActionPerformed
        VistaCliente vistaCliente = new VistaCliente(controladorCliente);
        dkpPrincipal.add(vistaCliente);
        vistaCliente.setVisible(true);
    }//GEN-LAST:event_mniClientesActionPerformed

    private void mniPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPedidosActionPerformed
        VistaPedido vistaPedidos = new VistaPedido(controladorPedido, controladorCliente, controladorRuta);
        dkpPrincipal.add(vistaPedidos);
        vistaPedidos.setVisible(true);
        
    }//GEN-LAST:event_mniPedidosActionPerformed

    private void mniChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChoferActionPerformed
        VistaChofer vistaChofer = new VistaChofer(controladorChofer, controladorBus);
        dkpPrincipal.add(vistaChofer);
        vistaChofer.setVisible(true);
    }//GEN-LAST:event_mniChoferActionPerformed

    private void mniRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRutaActionPerformed
        VistaDestinos vistaDestinos = new VistaDestinos(controladorRuta);
        dkpPrincipal.add(vistaDestinos);
        vistaDestinos.setVisible(true);
    }//GEN-LAST:event_mniRutaActionPerformed

    private void mniReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReservaActionPerformed
        VistaReserva vistaReserva = new VistaReserva(controladorReserva, controladorCliente, controladorBus, controladorRuta);
        dkpPrincipal.add(vistaReserva);
        vistaReserva.setVisible(true);
    }//GEN-LAST:event_mniReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dkpPrincipal;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mniBuses;
    private javax.swing.JMenuItem mniChofer;
    private javax.swing.JMenuItem mniClientes;
    private javax.swing.JMenuItem mniPedidos;
    private javax.swing.JMenuItem mniReserva;
    private javax.swing.JMenuItem mniRuta;
    private javax.swing.JMenu mnuOperaciones;
    private javax.swing.JMenu mnuRegistro;
    // End of variables declaration//GEN-END:variables
}
